### PR TITLE
C# IEnumerable<T> to TypeScript Array<T>

### PR DESCRIPTION
**Pull request by CADBIMDeveloper**
Hi @Elringus,

Current version generates something like:
```ts 
export function getSampleInputs(): System.Collections.Generic.IEnumerable<HelloWorld.Input>;
```
for 
```cs
[JSInvokable]
public static IEnumerable<Input> GetSampleInputs () => ...
```

This PR fixes that

### CODE REVIEW

**Comment by CADBIMDeveloper** [comment]
@Elringus , Ok, IList is a good idea, I'll make a fix a bit later

**Comment by Elringus** [comment]
`IReadOnlyList` and dictionary counterpart are already supported.

**Comment by Elringus** [comment]
I don't think supporting enumerable for interop in any capacity is a good idea, as it's very abstract.

**Comment by CADBIMDeveloper** [comment]
So, maybe `any` type in TS and compilation warnings via Roslyn analyzer then?

**Comment by Elringus** [comment]
Actually, I wonder why it's not already evaluating to `any` (it should do so with all the unsupported types). Probably a bug due to early generic case in `Convert` method. As for warning, the whole codegen module will likely be discarded when we migrate to the new .NET interop layer, so it's probably not invest into this much for now.

**Comment by CADBIMDeveloper** [comment]
Okay! Thank you! Waiting for .Net 7 support :-)

**Comment by CADBIMDeveloper** [comment]
Maybe it's still worth to add some more collections classes support, e.g. `IReadOnlyCollection<T>`, `ICollection<T>`? If it has `Count` property then it's something array-like?

**Comment by Elringus** [comment]
Just checked the enumerable<> case and indeed it's a bug; will look into this.

Regarding `ICollection`, it doesn't have indexer, so it's not exactly an array.

**Pull request closed without merging**
