### PR TITLE
Added some quality of life scripts

### PR DESCRIPTION
**Pull request by sharpninja**
# Added some quality of life scripts:

1. Build script for the samples (pwsh)
  * `-Automated` : Assumes CI/CD unattended build
  * `-Verbose` : Sets the verbosity for build output.
2. Build-All script to manage the whole project. (pwsh)
  * `-Automated` : Assumes CI/CD unattended build
  * `-Verbose` : Sets the verbosity for build output.
  * `-NoBuild` : Don't execute the build phases
  * `-Clean`: remove all artifacts.  Combine with `-NoBuild` to reset the directory.
3. BASH Build bootstrapper that ensures .Net 6.0 and Powershell are installed.  Passes through arguments to `build-all.ps1`.
4. GitHub Actions To build all projects.  **Does not** capture artifacts.

### CODE REVIEW

**Comment by Elringus** [comment]
Hey, Thanks for the PR! Unfortunately, I'm not familiar with powershell and won't be able to maintain the scripts.

We could however use a `build.sh` script at the root of the repository, which will build the JS runtime, compile test project and publish hello world sample.

As for CI, not sure what is the purpose of another bulid-only workflow. We already have codecov and codeql flows, that are building the solution. What could actually be useful, is a multi-platform build and test flow.

**Comment by sharpninja** [comment]
> We could however use a `build.sh` script at the root of the repository, which will build the JS runtime, compile test project and publish hello world sample.

The reason I built the scripts in Powershell was to allow building the project on Windows without installing WSL.  How about leaving the PS! files and I'll replicate them in BASH?

**Comment by sharpninja** [comment]
> As for CI, not sure what is the purpose of another bulid-only workflow. We already have codecov and codeql flows, that are building the solution. What could actually be useful, is a multi-platform build and test flow.

The purpose was to prove validity of the PowerShell scripts.

**Comment by sharpninja** [comment]
> Hey, Thanks for the PR! Unfortunately, I'm not familiar with powershell and won't be able to maintain the scripts.

I would be happy to take responsibility for those.

**Comment by Elringus** [comment]
Afaik, WSL is not required. For example, I'm running sh scripts via bash.exe bundled with git. I do get the UX concern, but I'm not comfortable with maintaining powershell stuff in this repo at the moment.

**Comment by sharpninja** [comment]
> Afaik, WSL is not required. For example, I'm running sh scripts via bash.exe bundled with git. I do get the UX concern, but I'm not comfortable with maintaining powershell stuff in this repo at the moment.

I created build.sh scripts to build the complete repository.

# Options

* `--automated` - Don't require user interaction
*  `--verbose` - Detailed build output
*  `--clean` - Remove all `bin`, `obj`, `dist`, and `node_modules` folders before building
* `--no-build` - Don't build but perform other specified stages, such as clean
* `--publish` - Not implemented.  Should spawn a separate script.

**Pull request closed without merging**
