### PR TITLE
patch dotnet.js to support strict mode

### PR DESCRIPTION
**Pull request by torgabor**

### CODE REVIEW

**Comment by Elringus** [comment]
Thank you. I'm not familiar with `patch` command. Will it work no matter the spacing/formatting of the target file? Actual output after building the runtime is not equal to what is currently stored in the repo, as I've formatted it for better readability during debug/discussions. Also, please move the `.patch` file to scripts directory, because the native dir is cleaned on runtime rebuild.

**Comment by torgabor** [comment]
Afaik the patch command should be resilient to small changes (like whitespace). It works together with the `diff` command, and `diff`-ing 2 files and applying the resulting patch to the first should produce identical output to the first.

The command I used to generate the patch is `diff -uwd dotnet.js dotnet2.js > strict.patch` where `dotnet2.js` is my originally manually modified file

**Comment by Elringus** [comment]
Just to be sure we have to check if it actually works. If you have time, please run the entire `compile-runtime.sh` and commit the resulting `dotnet.js`. Otherwise, we can leave the PR open and I'll test this when I have time.

**Comment by torgabor** [comment]
Well, I did make an earnest attempt at running `compile-runtime.sh`, but had no luck.
Running it on Ubuntu WSL1, I discovered it ships with a busted gzip that crashes instantly.
I tried upgrading it to WSL2, but the process has been going for 4 hours, and crashed after, taking the contents of my second SSD with it :(
I have an Ubuntu machine, where running the script produces the following error:
```
/home/torginus/DotNetJS/JavaScript/native/runtime/src/mono/mono.proj(105,5): error : The EMSDK_PATH environment variable should be set pointing to the emscripten SDK root dir.
`
I tried setting the `EMSDK_PATH` variable by hand, and calling the `emsdk_env.sh`, but nothing changed.

**Comment by torgabor** [comment]
I pushed the updated dotnet.js file.

**Comment by Elringus** [comment]
Here is the instructions on building the runtime: https://github.com/Elringus/DotNetJS#compiling-runtime Make sure to run `install-emsdk.sh` prior to compiling, it will take care of setting the env vars.

**Comment by torgabor** [comment]
Still, no luck..
It's complaining about the `EMSDK_PATH` path, same as before. This is on Ubuntu 22.04 I tried installing the emscripten from apt, that didn't fix it either.

**Comment by Elringus** [comment]
Ok, so I've tested and it doesn't seem to work. Here is the result of running the patch command:

```
patching file native/dotnet.js
Hunk #1 FAILED at 4398.
Hunk #2 FAILED at 4739.
Hunk #3 FAILED at 4778.
3 out of 3 hunks FAILED -- saving rejects to file native/dotnet.js.rej
```

In the attachement are the files generated by the command.
[dotnet.js.rej.txt](https://github.com/Elringus/DotNetJS/files/9220796/dotnet.js.rej.txt)
[dotnet.js.orig.txt](https://github.com/Elringus/DotNetJS/files/9220797/dotnet.js.orig.txt)

**Comment by Elringus** [comment]
I've also noticed that the auto-generated file has some random contents (hashes), so this kind of patching may not work.

**Comment by torgabor** [comment]
Hmm, for some reason, the [dotnet.js.orig.txt](https://github.com/Elringus/DotNetJS/files/9220797/dotnet.js.orig.txt) seems to be lacking newlines, while the one that's checked into `main` has them.
I'm trying to figure out why.

**Comment by Elringus** [comment]
> Actual output after building the runtime is not equal to what is currently stored in the repo, as I've formatted it for better readability during debug/discussions.

**Comment by Elringus** [comment]
Solved in #123.

**Pull request closed without merging**
