### PR TITLE
Added TypeScript declaration support for IReadOnlyList, IDictionary, IReadOnlyDictionary

### PR DESCRIPTION
**Pull request by Aragas**
I don't like the line duplication in 35 and 45, but overall looks decent
I'm aware there's a strict coding style, so feel free to edit the PR id needed!

### CODE REVIEW

**Comment by Elringus** [comment]
Not sure if .NET's JS interop will work with interfaces, have you actually tested it? Iirc, it throws polymorphic-something exception when attempting to bind a method with interface args.

**Comment by Aragas** [comment]
I haven't tested it with the branch, not sure how to pack it to use for self-hosted WASM generation, but I do have an IReadOnlyList property generated with the current `main` with wrong TS bindings. Everything seem to work correctly, the interface properties get serialized and deserialized

**Comment by Aragas** [comment]
Did a sanity check, the declaration files have `any` type instead of an array and node is seeing the props correctly

**Comment by Aragas** [comment]
But I didn't had a method with an interface signature tested

**Comment by Aragas** [comment]
Parameters and return interface types work

**Comment by Elringus** [comment]
Yeah, I've tested myself and it does seem to work with `IReadOnlyList`, at least. They probably have some pre-defined mappers for base collection interfaces.

**Comment by Elringus** [comment]
Fix the coverage and I think it'll be ok to merge.

**Comment by Aragas** [comment]
I'm not able to see the partially covered line, is codecov showing it for you?

**Comment by Elringus** [comment]
Nah, seems it hasn't processed it yet or something.

**Comment by Elringus** [comment]
Looks like it's throwing on `Packer.TypeUtilities.IsArray/IsDictionary...GetInterfaces()` due to incorrectly (?) stripped `System.Char`. Not happened previously because we had `IsGenericType` check before invoking `GetInterfaces()`, but it's not necessary now. I'd just leave it as a hack, but not sure how to test this.

```
/home/runner/work/DotNetJS/DotNetJS/DotNet/DotNetJS/build/DotNetJS.targets(23,9): error MSB4018: System.TypeLoadException: Could not find type 'System.Char' in assembly '/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/bin/Release/net6.0/publish/wwwroot/_framework/System.Runtime.dll'. [/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/Test.Main.csproj]
/home/runner/work/DotNetJS/DotNetJS/DotNet/DotNetJS/build/DotNetJS.targets(23,9): error MSB4018:    at System.Reflection.MetadataLoadContext.GetCoreType(CoreType coreType) [/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/Test.Main.csproj]
/home/runner/work/DotNetJS/DotNetJS/DotNet/DotNetJS/build/DotNetJS.targets(23,9): error MSB4018:    at System.Reflection.TypeLoading.Ecma.EcmaModule.GetPrimitiveType(PrimitiveTypeCode typeCode) [/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/Test.Main.csproj]
/home/runner/work/DotNetJS/DotNetJS/DotNet/DotNetJS/build/DotNetJS.targets(23,9): error MSB4018:    at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeType(BlobReader& blobReader, Boolean allowTypeSpecifications, Int32 typeCode) [/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/Test.Main.csproj]
/home/runner/work/DotNetJS/DotNetJS/DotNet/DotNetJS/build/DotNetJS.targets(23,9): error MSB4018:    at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeTypeSequence(BlobReader& blobReader) [/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/Test.Main.csproj]
/home/runner/work/DotNetJS/DotNetJS/DotNet/DotNetJS/build/DotNetJS.targets(23,9): error MSB4018:    at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeGenericTypeInstance(BlobReader& blobReader) [/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/Test.Main.csproj]
/home/runner/work/DotNetJS/DotNetJS/DotNet/DotNetJS/build/DotNetJS.targets(23,9): error MSB4018:    at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeType(BlobReader& blobReader, Boolean allowTypeSpecifications, Int32 typeCode) [/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/Test.Main.csproj]
/home/runner/work/DotNetJS/DotNetJS/DotNet/DotNetJS/build/DotNetJS.targets(23,9): error MSB4018:    at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeType(BlobReader& blobReader, Boolean allowTypeSpecifications) [/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/Test.Main.csproj]
/home/runner/work/DotNetJS/DotNetJS/DotNet/DotNetJS/build/DotNetJS.targets(23,9): error MSB4018:    at System.Reflection.Metadata.TypeSpecification.DecodeSignature[TType,TGenericContext](ISignatureTypeProvider`2 provider, TGenericContext genericContext) [/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/Test.Main.csproj]
/home/runner/work/DotNetJS/DotNetJS/DotNet/DotNetJS/build/DotNetJS.targets(23,9): error MSB4018:    at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveTypeSpec(TypeSpecificationHandle handle, EcmaModule module, TypeContext& typeContext) [/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/Test.Main.csproj]
/home/runner/work/DotNetJS/DotNetJS/DotNet/DotNetJS/build/DotNetJS.targets(23,9): error MSB4018:    at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveTypeDefRefOrSpec(EntityHandle handle, EcmaModule module, TypeContext& typeContext) [/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/Test.Main.csproj]
/home/runner/work/DotNetJS/DotNetJS/DotNet/DotNetJS/build/DotNetJS.targets(23,9): error MSB4018:    at System.Reflection.TypeLoading.Ecma.EcmaDefinitionType.SpecializeInterfaces(RoType[] instantiation)+MoveNext() [/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/Test.Main.csproj]
/home/runner/work/DotNetJS/DotNetJS/DotNet/DotNetJS/build/DotNetJS.targets(23,9): error MSB4018:    at System.Reflection.TypeLoading.RoType.ComputeInterfaceClosure() [/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/Test.Main.csproj]
/home/runner/work/DotNetJS/DotNetJS/DotNet/DotNetJS/build/DotNetJS.targets(23,9): error MSB4018:    at System.Reflection.TypeLoading.RoType.GetInterfacesNoCopy() [/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/Test.Main.csproj]
/home/runner/work/DotNetJS/DotNetJS/DotNet/DotNetJS/build/DotNetJS.targets(23,9): error MSB4018:    at System.Reflection.TypeLoading.RoType.GetInterfaces() [/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/Test.Main.csproj]
/home/runner/work/DotNetJS/DotNetJS/DotNet/DotNetJS/build/DotNetJS.targets(23,9): error MSB4018:    at Packer.TypeUtilities.IsArray(Type type) in /home/runner/work/DotNetJS/DotNetJS/DotNet/Packer/Utilities/TypeUtilities.cs:line 19 [/home/runner/work/DotNetJS/DotNetJS/JavaScript/test/csharp/Test.Main/Test.Main.csproj]
```

**Comment by Elringus** [comment]
Ok, so looks like that is the correct way to solve this. We'll use the non-stripped assemblies from .NET runtime folder for the inspection/packaging steps. Hopefully this won't break something else.

**Pull request merged**
